/*
 * trafoGuardPage.c
 *
 *  Created on: 19. jan. 2010
 *      Author: Ernad
 */
#include <stdio.h>
#include <string.h>
#include "trafoGuardPage.h"
char currDate[20];
char currTime[20];

int trafoGuardPage_getRightBlock(char **postvars) {
	printf("<head>\r\n");
	printf("<title>ImedSecure webserver</title>\r\n");
	printf("<meta http-equiv=\"Content-Type\" content=\"text/html; utf-8\" />\r\n");
	printf("<meta http-equiv=\"Pragma\" content=\"no-cache\" />\r\n");
	printf("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/favicon.ico\">\r\n");
	printf("<link rel=\"stylesheet\" type=\"text/css\" href=\"imed.css\"/>\r\n");
	printf("<link rel=\"stylesheet\" type=\"text/css\" href=\"tree_styles.css\"/>\r\n");



	////// ENO TEST
	printf("<script type=\"text/javascript\">");

			printf("function loadXMLDoc(url)");
			printf("{if (window.XMLHttpRequest)");
			printf("{ xmlhttp=new XMLHttpRequest();}");
			printf("else {xmlhttp=new ActiveXObject(\"Microsoft.XMLHTTP\");}");
			printf(" xmlhttp.open(\"POST\",url,true);");
			printf(" xmlhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');");

			printf("xmlhttp.onreadystatechange = function() {");
			printf("if (xmlhttp.readyState == 4) { ");
			printf("updatepage(xmlhttp.responseText); }} ");

			printf("xmlhttp.send(null);}");

			printf("function updatepage(str){ ");
			printf("document.getElementById('test').innerHTML=xmlhttp.responseText;}");

			printf("</script>");



	///// END TEST



	printf("<script type=\"text/javascript\" src=\"cooltreepro_uncompressed.js\"></script>\r\n");
	printf("<script type=\"text/javascript\" src=\"tree_format.js\"></script>\r\n");
	printf("<script type=\"text/javascript\" src=\"tree_nodes.js\"></script>\r\n");
	printf("<script type=\"text/javascript\" src=\"tree_format_setup.js\"></script>\r\n");
	printf("<script type=\"text/javascript\" src=\"tree_tg_setup.js\"></script>\r\n");
	printf("<script type=\"text/javascript\" src=\"simpletreemenu.js\"> </script>\r\n");
	printf("<script type=\"text/javascript\" src=\"popUps.js\"></script>\r\n");
	printf("<!--[if lte IE 6]>\r\n");
	printf("<style type=\"text/css\" media=\"screen, projection, tv\">\r\n");
	printf("#wrapper {\r\n");
	printf("height: expression( (document.body.clientHeight) ? document.body.clientHeight * 0.9 + 'px' : document.documentElement.clientHeight * 0.9 + 'px' );\r\n");
	printf("}\r\n");
	printf("#nav {\r\n");
	printf("height: expression( document.all.wrapper.offsetHeight + 'px' );\r\n");
	printf("}\r\n");
	printf("#content {\r\n");
	printf("height: expression( document.all.wrapper.offsetHeight + 'px' );\r\n");
	printf("}\r\n");
	printf("</style>\r\n");
	printf("<![endif]-->\r\n");
	printf("<meta http-equiv=\"Page-Enter\" content=\"blendTrans(Duration=2)\"/>\r\n");
	printf("<meta http-equiv=\"Site-Exit\" content=\"blendTrans(Duration=5)\"/>\r\n");
	printf("</head>\r\n");
	printf("<body>\r\n");
	printf("<div id=\"wrapper\">\r\n");
	printf("<!--<p id=\"headline\">&copy; ImedSecure.</p>-->\r\n");
	printf("<div id=\"header\">\r\n");
	printf("<script type=\"text/javascript\" src=\"header.js\"></script>\r\n");
	printf("</div>\r\n");
	printf("<div id=\"content\">\r\n");
	printf("<!--	  TRAFOGUARD SETUP	 -->\r\n");
	printf("<table id=\"mytable\" cellspacing=\"0\">\r\n");
	printf("<caption><img src=\"images/page_white_wrench.png\" width=\"16\" height=\"16\" alt=\"\" align=\"top\" />    Trafoguard setup      <A HREF=\"tg_setup_hlp.htm\" onClick=\"return popup(this, 'notes2') \"><img src=\"images/help.png\" width=\"16\" height=\"16\" alt=\"\" align=\"top\" border=\"0\"/></A></caption>\r\n");
	printf("</table>\r\n");
	//printf("<form action=\"../cgi-bin/mycgi.cgi\">\r\n");
	// ENO
	printf("<form action=\"javascript:loadXMLDoc('cgiTrafoguard')\">\r\n");

	printf("<script>\r\n");
	printf("var tree2 = new COOLjsTreePRO(\"tree2\", TREE_TG_SETUP, TREE_FORMAT_SETUP);\r\n");
	printf("tree2.init();\r\n");
	printf("</script>\r\n");
	printf("<div id=\"contentfooter\" style=\"padding-left:30px;\">\r\n");
	printf("<INPUT TYPE=SUBMIT VALUE=\"Submit\" class=\"btn\" onmouseover='this.className=\"btn btnhov\"' onmouseout='this.className=\"btn\"'>\r\n");
	printf("</div>\r\n");
	printf("</form>\r\n");
	printf("</div><!-- content -->\r\n");
	printf("<div id=\"menu\">\r\n");
	printf("<!--<script type=\"text/javascript\" src=\"menu.js\"></script>-->\r\n");
	printf("<script>\r\n");
	printf("var tree1 = new COOLjsTreePRO(\"tree1\", TREE_NODES, TREE_FORMAT);\r\n");
	printf("tree1.init();\r\n");
	printf("</script>\r\n");
	printf("</div><!-- menu -->\r\n");
	printf("<div id=\"footer\">\r\n");
	printf("<script type=\"text/javascript\" src=\"footer.js\"></script>\r\n");
	printf("</div>\r\n");
	printf("</div><!-- wrapper -->\r\n");
	printf("<script type=\"text/javascript\">\r\n");
	printf("<!--ddtreemenu.createTree(\"treemenu2\", true)-->\r\n");
	printf("<!--ddtreemenu.createTree(\"treemenu1\", true)-->\r\n");
	printf("</script>\r\n");
	printf("</body>\r\n");
	printf("</html>\r\n");

	/*printf("<div id=\"right\">\r\n");
	printf("<h1>IMED Secure Gateway</h1>\r\n");
	printf("<div id=\"h_line\"></div>\r\n");
	printf("<div id=\"hh1\"><h1>MEASUREMENTS</h1><h2>");
	//31.12.2009</h2><h2>12:00:00</h2></div>\r\n");
	getParams("TIME\n", currDate, currTime);
	printf(currDate);
	printf("</h2><h2>");
	printf(currTime);
	printf("</h2></div>\r\n");

	printf("<div id=\"distL\"></div>\r\n");
	printf("<div id=\"hh1\"><h1>Supply 1</h1><h2>230Vac</h2><h3>Preferred main supply</h3></div>\r\n");
	printf("<div id=\"hh1\"><h1>Supply 2</h1><h2>230Vac</h2><h3>Secondary safety supply 1</h3></div>\r\n");
	printf("<div id=\"hh1\"><h1>Supply 3</h1><h2>230Vac</h2><h3>Secondary safety supply 2</h3></div>\r\n");
	printf("<div id=\"hh1\"><h1>Supply 4</h1><h2>230Vac</h2><h3>Downstream IT net voltage</h3></div>\r\n");
	printf("<form name=\"refresh\" id=\"refresh\" method=\"post\" action=\"Trafoguard.html\">\r\n");
	printf("<div  style=\"float:left; width:50%\">\r\n");
	printf("<h3>Push the refresh button to update the measurements</h3></div>\r\n");
	printf("<div  style=\"float:left; width:50%\"><input type=\"submit\" name=\"Submit\" value=\"Refresh\" /></div>\r\n");
	printf("</form>\r\n");
	printf("<div id=\"dist\"></div>\r\n");
	printf("<div id=\"hh1\"><h1>Unit info</h1></div>\r\n");
	printf("<div id=\"distL\"></div>\r\n");
	printf("<div id=\"hh1\"><h1>Type</h1><h2>SU-0901</h2></div>\r\n");
	printf("<div id=\"hh1\"><h1>Hardware revision</h1><h2>1.01</h2></div>\r\n");
	printf("<div id=\"hh1\"><h1>Firmware revision</h1><h2>1.02</h2></div>\r\n");
	printf("<div id=\"hh1\"><h1>Serial  number</h1><h2>12334567890</h2></div>\r\n");
	printf("<div style=\"float:left; width:100%\"><h1>SwitchoverUnit Setup</h1></div>\r\n");
	printf("<form method=\"post\" onsubmit=\"return validate_form()\" name=\"conf\" action=\"Trafoguard.html\">\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION >Language </CAPTION>\r\n");
	printf("<tr >\r\n");
	printf("<th id=\"aa\">Set menu language</th>\r\n");
	printf("<th id=\"a\">\r\n");
	printf("<select name=\"state\" id=\"state\" tabindex=\"5\">\r\n");
	printf("<option value=\"EN\">English</option>\r\n");
	printf("<option value=\"GE\" >Deutsch</option>\r\n");
	printf("<option value=\"NO\" >Norsk</option>\r\n");
	printf("</select>\r\n");
	printf("</th>\r\n");
	printf("<th id=\"aa\"> </th>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<caption >Alarm</caption>\r\n");
	printf("<tr >\r\n");
	printf("<th id=\"aa\">Alarm Messages</th>\r\n");
	printf("<th id=\"a\">Failure</th>\r\n");
	printf("<th id=\"a\">Alarm</th>\r\n");
	printf("<th id=\"aa\">Description</th>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td>Alarm message</td>\r\n");
	printf("<td><input type=\"text\" maxlength=\"24\" name=\"aMf\" id=\"aMf\" title=\"Max 24 char A-z 0-9 and .-\" ONCHANGE=\"vA(this, true)\";/></td>\r\n");
	printf("<td><input type=\"text\" maxlength=\"24\" name=\"aMa\" id=\"aMa\" title=\"Max 24 char A-z 0-9 and .-\" ONCHANGE=\"vA(this, true)\";/></td>\r\n");
	printf("<td id=\"inf_email\">This message will be displayed on the AlarmPanel</td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td>Alarm message overload alarm</td>\r\n");
	printf("<td><input type=\"text\" maxlength=\"24\" name=\"aOf\" id=\"aOf\" title=\"Max 24 char A-z 0-9 and .-\" ONCHANGE=\"vA(this, true)\";/></td>\r\n");
	printf("<td><input type=\"text\" maxlength=\"24\" name=\"aOa\" id=\"aOa\" title=\"Max 24 char A-z 0-9 and .-\" ONCHANGE=\"vA(this, true)\";;/></td>\r\n");
	printf("<td>This message will be displayed on the AlarmPanel</td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td height=\"28\">Alarm message high temperature</td>\r\n");
	printf("<td><input type=\"text\" maxlength=\"24\" name=\"aHf\" id=\"aHf\" title=\"Max 24 char A-z 0-9 and .-\" ONCHANGE=\"vA(this, true)\";/></td>\r\n");
	printf("<td><input type=\"text\" maxlength=\"24\" name=\"aHa\" id=\"aHa\" title=\"Max 24 char A-z 0-9 and .-\" ONCHANGE=\"vA(this, true)\";/></td>\r\n");
	printf("<td>This message will be displayed on the AlarmPanel</td>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION >Password </CAPTION>\r\n");
	printf("<tr >\r\n");
	printf("<td id=\"aa\">Unit password</td>\r\n");
	printf("<td id=\"a\"><input type=\"text\" maxlength=\"4\" name=\"alMsgFeil\" id=\"alMsgFeil\" value=\"imed\" title=\"Max 4 char A-z\" ONCHANGE=\"vP(this, true)\"/></td>\r\n");
	printf("<td id=\"aa\"> Password to access the SETUP menu on the unit</td>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION >Unit name / Id </CAPTION>\r\n");
	printf("<tr >\r\n");
	printf("<td id=\"aa\">Edit unit name / Id</th>\r\n");
	printf("<td id=\"a\"><input type=\"text\" name=\"alMsgFeil\" id=\"alMsgFeil\"  maxlength=\"24\" title=\"Max 24 char A-z 0-9 and .-\" ONCHANGE=\"vA(this, true)\";/></th>\r\n");
	printf("<td id=\"aa\"> </th>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION >NCAN bus</CAPTION>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Address</td>\r\n");
	printf("<td id=\"a\"><input type=\"text\" name=\"alMsgFeil\" id=\"alMsgFeil\" value=\"3\" maxlength=\"3\" title=\"Range 1-127\" ONCHANGE=\"v0(this, true)\";/></td>\r\n");
	printf("<td id=\"aa\">Do not change</td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Enabeled</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\">Yes</option>\r\n");
	printf("<option value=\"1\" >No</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\">If no, the unit will be disconnected from the N_CAN bus</td>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION >Options</CAPTION>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Display timeout</td>\r\n");
	printf("<td id=\"a\"><input type=\"text\" name=\"alMsgFeil\" id=\"alMsgFeil\" value=\"300\" maxlength=\"3\" title=\"Range 0-300 0=OFF\" ONCHANGE=\"v1(this, true)\";/></td>\r\n");
	printf("<td id=\"aa\">If 0 screensaver disabled</td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Display contrast</td>\r\n");
	printf("<td id=\"a\"><input type=\"text\" name=\"alMsgFeil\" id=\"alMsgFeil\" value=\"13\" maxlength=\"2\" title=\"Range 1-15\" ONCHANGE=\"v2(this, true)\";/></td>\r\n");
	printf("<td id=\"aa\">OLED display contrast on unit</td>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION >Contactor 1 setup</CAPTION>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Type</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Pullup</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Inverted</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Alarm message</td>\r\n");
	printf("<td id=\"a\"><input type=\"text\" name=\"alMsgFeil\" id=\"alMsgFeil\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION >Contactor 2 setup</CAPTION>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Type</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Pullup</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Inverted</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Alarm message</td>\r\n");
	printf("<td id=\"a\"><input type=\"text\" name=\"alMsgFeil\" id=\"alMsgFeil\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION >Contactor 3 setup</CAPTION>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Enabled</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Type</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Pullup</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Inverted</td>\r\n");
	printf("<td id=\"a\"><select name=\"enabled\" id=\"enabled\" tabindex=\"5\">\r\n");
	printf("<option value=\"0\" >No</option>\r\n");
	printf("<option value=\"1\">Yes</option>\r\n");
	printf("</select></td>\r\n");
	printf("<td id=\"aa\"><input type=\"text\" name=\"alMsgAlarm\" id=\"alMsgAlarm\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">Alarm message</td>\r\n");
	printf("<td id=\"a\"><input type=\"text\" name=\"alMsgFeil\" id=\"alMsgFeil\"/></td>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION>Switchover levels</CAPTION>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\"></td>\r\n");
	printf("<td id=\"a\"></td>\r\n");
	printf("<td id=\"aa\"></td>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<table id=\"myTable2\">\r\n");
	printf("<CAPTION>Switchover delays</CAPTION>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">toff k1</td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">toff k2</td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">toff k1Â to ton k2 and vice versa</td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">toff k2 to ton k3 and vice versa</td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">ton k2</td>\r\n");
	printf("</tr>\r\n");
	printf("<tr>\r\n");
	printf("<td id=\"aa\">ton k3</td>\r\n");
	printf("</tr>\r\n");
	printf("</table>\r\n");
	printf("<div style=\"width:100%; float:left; margin:auto\">\r\n");
	printf("<input type=\"reset\" name=\"Cancel\" value=\"Cancel\"/>\r\n");
	printf("<input type=\"submit\" name=\"Reload\" value=\"Reload\" />\r\n");
	printf("<input type=\"submit\" name=\"SaveAll\" value=\"Save All\"/>\r\n");
	printf("</div>\r\n");
	printf("</form>\r\n");
	printf("</div>\r\n");
	printf("</div>\r\n");
	printf("</div>\r\n");
*/
	return 0;
}
