/*
 * nothing.h
 *
 *  Created on: 10. mars 2010
 *      Author: Ernad
 */

#ifndef NOTHING_H_
#define NOTHING_H_

#define MAJOR_NUM  				98

enum SJA1000_REG {
	CONTROL_REG = 0,
	COMMAND_REG,
	STATUS_REG,
	INTERRUPT_REG,
	ACCEPTANCE_CODE_REG,
	ACCEPTANCE_MASK_REG,
	BUS_TIMING_0_REG,
	BUS_TIMING_1_REG,
	OUTPUT_CONTR_REG,
	TEST_REG,
	TRANSMIT_IDENTIFIER_H_REG,
	TRANSMIT_IDENTIFEIER_L_REG,
	TRANSMIT_BYTE_1_REG,
	TRANSMIT_BYTE_2_REG,
	TRANSMIT_BYTE_3_REG,
	TRANSMIT_BYTE_4_REG,
	TRANSMIT_BYTE_5_REG,
	TRANSMIT_BYTE_6_REG,
	TRANSMIT_BYTE_7_REG,
	TRANSMIT_BYTE_8_REG,
	RECEIVE_IDENTIFIER_H_REG,
	RECEIVE_IDENTIFEIER_L_REG,
	RECEIVE_BYTE_1_REG,
	RECEIVE_BYTE_2_REG,
	RECEIVE_BYTE_3_REG,
	RECEIVE_BYTE_4_REG,
	RECEIVE_BYTE_5_REG,
	RECEIVE_BYTE_6_REG,
	RECEIVE_BYTE_7_REG,
	RECEIVE_BYTE_8_REG,
	NOT_USED_REG,
	CLOCK_DIVIDER_REG
};

#define IOCTL_GET  _IOWR(MAJOR_NUM, 1, struct canControlMsg)
#define IOCTL_SET  _IOWR(MAJOR_NUM, 2, struct canControlMsg)
#define IOCTL_TEST _IOWR(MAJOR_NUM, 3, int)

struct canControlMsg {
   char address;
   char newValue;
   char result[8];
   char resultLength;
   int id;
};

#endif /* NOTHING_H_ */
